### ISSUE TITLE
Math

### ISSUE THREAD

**Issue by ep12** [dylanbeattie/rockstar#12]
Currently, increment, decrement and assignment are the only possible math operations. It might be somehow inconvenient that way to calculate roots. Especially if all the required functions have to be written in rockstar. This would be the lyrics for a day-long song...

**Comment by ep12** [comment]
Oh, Take {a} from {b} is not documented....

**Comment by N-Masi** [comment]
You're right in that there are no other mathematical operators documented which is a bit of an issue. I think in addition to having ```Take {a} from {b}``` for subtraction you could also have:

Addition: ```Put {a} with {b}```
e.g. ```Put your heart with mine```

Division: ```Break {a} into {b} pieces```
e.g. ```Break my heart into many pieces```

Multiplication: ```Do {a} for {b}```
e.g. ```Do anything for you```

**Comment by dylanbeattie** [comment]
`Take {a} from {b}` is actually a statement rather than an expression, because it decrements the value of `b` by `a` but doesn't return anything. And you're right, it's not documented. I actually think it's a bit weird so let's add support for proper arithmetic expressions instead...

Arithmetic expressions:

* `{a} plus {b}` - addition. Alias `with`
* `{a} minus {b}` - subtraction. Alias `without`
* `{a} times {b}` - multiplication. Alias `of`
* `{a} over {b}` - division.

Examples:

* `Put the whole of your heart into my hands` - multiply `your heart` by `the whole` and assign the result to `my hands`

* `My world is nothing without your love` - Initialize `my world` with the result of subtracting `your love` from 0

* `If the tears of a child is nothing` - check whether `the tears` * `a child` = 0
