### ISSUE TITLE
Do function calls allow "and" for separating arguments?

### ISSUE THREAD

**Issue by wizered67** [dylanbeattie/rockstar#130]
When describing function calls, the spec doesn't explicitly say what can separate arguments, but both examples given use commas, such as `Multiply taking 3, 5`.  However, the minimalist (non-idiomatic) fizzbuzz code includes `If Modulus taking Counter and Fizz is 0` which seems to call the Modulus function with Counter and Fizz as arguments. This seems like it creates an ambiguity since the line could be interpreted as `if Modulus(Counter, Fizz) == 0` and `if Modulus(Counter) && Fizz == 0`.

To get to my actual question, is it intentional that "and" is used as an argument separator in function calls in one of the examples, or does Rockstar only support using commas to separate arguments?

**Comment by cwfitzgerald** [comment]
The webpiler allows for both `and` and `,` to separate arguments because of those exact examples. I have written up a full spec about order of operations, type conversions, and things like that in #97. There hasn't been much hubub about that, so either it's been agreed upon, or I just haven't drummed up enough about it.

If the changes I propose in #97 get merged, it will solve this issue.

**Comment by young-steveo** [comment]
Actually I missed this ambiguity so thrash uses `and` for definition of params and `,` for calling params, but not vice-versa.  Do we have boolean operators?

**Comment by cwfitzgerald** [comment]
Afaik, yes we do. See #97.
