### ISSUE TITLE
Blank line placement in example

### ISSUE THREAD

**Issue by drewajp** [dylanbeattie/rockstar#29]
The current example has
 ```
Give back your heart
{blank line}
{blank line}
Desire is a lovestruck ladykiller
```
It should be 
```
Take your soul from your heart 
{blank line} 
Give back your heart 
{blank line} 
Desire is a lovestruck ladykiller
```

since it should return the the value after exiting the `while` loop

**Comment by dylanbeattie** [comment]
You're absolutely right - fix incoming.

Also, you can include code blocks in issues by enclosing them in triple backticks

```
like this
```

:)

**Comment by N-Masi** [comment]
I think there's even more issues. The actual FizzBuzzing part of the example involves nested blocks, there's the main ```Until my world is Desire``` block and the 3 nested ```If``` blocks. However there is no documentation for using nested blocks. If I were to make a suggestion it would be to bring back the reserved ```and``` and use it such that each loop would only execute the line below it (such as If statements do in Java) as well as any lines below it that start with ```and``` up until there is a line that doesn't begin with ```and```. So the issue you pointed out would be alleviated because the while loop would only execute the next line (```Take your soul from your heart```) and wouldn't move on the the ```Give``` statement until the while statement was broken because there's no ```and``` in front of the ```Give```.

**Comment by wolfgang42** [comment]
@N-Masi How does that work with nested blocks, though? If you have leading `And`s, there's no way to close an inner block without closing the outer block.

**Comment by N-Masi** [comment]
@wolfgang42 You know that's a good point and after thinking about it for a bit and looking at Dylan's fix I think his idea of just using blank lines to denote the end of blocks works way better than mine due to what you just pointed out. Though I wonder if you could replace the blank line with some sort of phrase such as ```That's the end of that``` or something else more poetically inspired.
