### ISSUE TITLE
Ignore lines that don't fit the spec

### ISSUE THREAD

**Issue by Michaelkielstra** [dylanbeattie/rockstar#98]
Constraining rock stars to a single language specification feels dangerously close to being [The Man](https://www.youtube.com/watch?v=u5JAQGUyIPE).  I propose that we specify that, if a compiler cannot understand a line, it just skips it, and any related warning messages must be turned off by default.  For example, staying on our theme, currently the result of a compiler coming across the line "Stick it to the man" is implementation-dependant and will probably give an error.  Since when does the compiler have the right to tell you what you can and can't say?

This will of course make development slightly more difficult as the compiler cannot catch syntax errors by default, but, for those who want to be safe and traditional, I don't forsee any problems with a flag or other option for turning the errors back on.  After all, not all rock stars write in the same style.

**Comment by Michaelkielstra** [comment]
This will also make it much easier to do bulk analysis to find actual rock songs that are valid programs.

**Comment by yanorestes** [comment]
That really wouldn't be good. If you want a line that doesn't follow the specs, make it follow the specs using comments. rockstar-py, for example, won't give an error while parsing this line. Instead, it would write the exact line to the .py file and the error would only turn up when you tried to execute the Python file. The transpiler doesn't check if a line is valid, it just makes the needed substitutions and conversions

**Comment by Michaelkielstra** [comment]
I was thinking more about those compilers or interpreters that try to "understand" the language through a full parser.  My idea was that comments would still be used for things such as "XYZ is the variable that stores ABC", since that would be a valid line of code otherwise, but those lines that made no sense at all could be ignored.  That way, you could write and debug with the "give error on bad line" switch activated, but, before publishing your code, you could add other lines to make the lyrics more meaningful and your code would still work out-of-the-box with default settings.

**Comment by cwfitzgerald** [comment]
I'm going to agree with @yanorestes and _strongly_ advise against it. Sure it can be implemented in either a transpiler or a parser, but it won't be easy. Backtracing recursive decent parsers (like the one I have) are told to stop backtracing at some point because it would be pointless to try other things, both making the error messages worse, and forcing the compiler to take a lot longer to parse the language. There's also something that feels just wrong about having a language that just throws away anything it doesn't understand indiscriminately. Especially when you have multiple competing implementations which each have their own set of quirks and problems having zero error messages seems like a recepie for people thinking all of the implementations are wrong when their code compiles, but does nothing interesting.

**Comment by dylanbeattie** [comment]
No. For several reasons.

First, if you can write ANYTHING, then you can put `shout "Hello World"` at the top of any old bunch of lyrics and claim it's a valid Rockstar program. The fun of Rockstar is in trying to be creative within the constraints imposed by the language.

Second, this not only makes it much harder to implement any kind of lexer or parser, but also means if you make a typo or a syntax error, the compiler will silently ignore the entire line containing your error. This would be frustrating at best, and at worst could result in all sorts of unexpected behaviour - if your typo was in the guard clause around a destructive operation or the check for the base case in a recursive function, this could be quite dangerous.

Third, if you take all the rules away, you'll end up with [free jazz](https://www.youtube.com/watch?v=U_oVGUwNjcI), and that's just not how we do things around here.
